version: '3.8'
services:
  grafana:
    image: grafana/grafana:10.1.5
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin